remote_theme: just-the-docs/just-the-docs
title: "unicornpkg"
exclude:
  - .obsidian/
  - CNAME
  - .git*
aux_links:
  "unicornpkg on GitHub":
    - "//github.com/unicornpkg"
  "Roadmap":
    - "//github.com/orgs/unicornpkg/projects/1"
